name: ft
description: A new Flutter project.
version: 2.0.11+7

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.3.4
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.0.3
  geolocator: ^8.2.1
  get_it: ^7.2.0
  hive: ^2.2.1
  intl: ^0.17.0
  json_annotation: ^4.5.0
  mask_text_input_formatter: ^2.3.0
  mockito: ^5.2.0
  path_provider: ^2.0.11
  qr_code_scanner: ^1.0.0
  rxdart: ^0.27.4
  signature: ^5.0.1
  url_launcher: ^6.1.4
  change_app_package_name: ^1.1.0
  dropdown_search: ^5.0.2
  easy_debounce: ^2.0.2+1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.3
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  json_serializable: ^6.2.0

flutter_native_splash:
  image: lib/assets/images/login/splash.png
  color: "#32333D"
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/login/launcher.png"
  adaptive_icon_background: "#32333D"
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/main/
    - lib/assets/images/home/
    - lib/assets/images/device/
    - lib/assets/images/schedule/
    - lib/assets/icon/inventory/
    - lib/assets/icon/
    # - lib/assets/images/inventory/
    - lib/assets/images/login/
    # - lib/assets/images/home/
  # - assets/images/home/scene/
  # - assets/images/account/
  # flutter pub run flutter_native_splash:create
